version: '3.8'
services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - db
  db:
    image: pg_postgis_17:latest
    build:
      context: .
      dockerfile: Dockerfile.postgis
    restart: unless-stopped
    container_name: mirsha_db
    environment:
      - POSTGRES_DB=vet_epigeoai_db
      - POSTGRES_USER=vet_user
      - POSTGRES_PASSWORD=strongpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
